version: '3.5' 
services: 
  db_pg: 
    container_name: postgres_nestjs
    image: postgres 
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        # - ./pgdata:/var/lib/postgresql/data 
        - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' 
    environment:
      AP_NAME: ${AP_NAME}
      AP_VERSION: ${AP_VERSION}
      APP_TITLE: ${APP_TITLE}
      APP_DESCRIPTION: ${APP_DESCRIPTION}
      APP_PORT: ${APP_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db_pg
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DEFAULT_USER: ${DEFAULT_USER}
      DEFAULT_USER_EMAIL: ${DEFAULT_USER_EMAIL}
      DEFAULT_USER_PASSWORD: ${DEFAULT_USER_PASSWORD}
      ALGORITHM: ${ALGORITHM}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${DREFRESH_TOKEN_EXPIRE_MINUTES_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_TRANSPORT: ${MAIL_TRANSPORT}

# nest-backend:
#   container_name: nest-app
#   image: nest-api
#   build:
#     dockerfile: Dockerfile
#     context: .
#   ports:
#     - '3000:3000' 
#   depends_on: 
#     - database_postgres 
#   volumes:
#       - ./src:/app/src 

# app: 
#  build: 
#   context: . 
#   dockerfile: Dockerfile 
#  container_name: nest-docker-postgres 
#  environment: 
#    - PORT=${PORT} 
#  ports: 
#    - '3000:3000' 
#  depends_on: 
#    - db 
#  volumes:
#     - ./src:/app/src 
# pgadmin:
#  image: dpage/pgadmin4 
#  restart: always 
#  container_name: nest-pgadmin4 
#  Environment:
#    - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
#    - PGADMIN_DEFAULT_PASSWORD=pgadmin4 
# ports: 
#    - '5050:80' 
# depends_on: 
#     - db