export const PROVIDERS_NAMES = {
    SEQUELIZE: 'SEQUELIZE',
    COMMUN_CATALOGUE:  'COMMUN_CATALOGUE',
    COMMUN_COMPANY: 'COMMUN_COMPANY',
    SECURITY_ROLE :  'SECURITY_ROLE',
    SECURITY_USER :  'SECURITY_USER',
    SECURITY_USERS_IN_ROLES :  'SECURITY_USERS_IN_ROLES',
}
